apiVersion: v1
kind: Service
metadata:
  name: iris-classifier
  labels:
    app: iris-classifier
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 5000
    protocol: TCP
  selector:
    app: iris-classifier